-- AlterEnum
DO $$ BEGIN
  ALTER TYPE "NotificationType" ADD VALUE 'PAYMENT_DISPUTED';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE "NotificationType" ADD VALUE 'BANK_ACCOUNT_UPDATED';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
