services:
  - type: web
    name: savepal-backend
    env: node
    region: oregon
    plan: free
    buildCommand: NODE_ENV=development && cd packages/backend && npm install && npx prisma generate && npm run build
    startCommand: NODE_ENV=production && cd packages/backend && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
